version: '3.11'

services:
  web:
    build: .
    volumes:
     - .:/app
    ports:
     - 8000:8000
    env_file:
     - ./.env
    image: app:djandock
    container_name: DDS_app_Container
    command: gunicorn --bind 0.0.0.0:8000 PredictDai.wsgi
    depends_on:
     - postgres
  nginx:
    build: ./nginx
    ports:
     - 8080:8080
    container_name: DDS_nginx
    depends_on:
      - web
    restart: always
  postgres:
    image: postgres:16
    env_file:
     - .env
    container_name: DDS_postgres
    restart: always
    environment:
     POSTGRES_USER: someuser
     POSTGRES_PASSWORD: password
     POSTGRES_DB: somedatabase
    ports:
     - "5432:5432"


