# Generated by Django 4.2.3 on 2023-11-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pdai', '0003_rf_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='rf_model',
            name='RF_prob',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
