# Generated by Django 4.2.3 on 2023-11-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pdai', '0007_alter_rf_model_hba1c_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rf_model',
            name='bmi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rf_model',
            name='hypertension',
            field=models.IntegerField(),
        ),
    ]
