# Generated by Django 4.2.3 on 2024-04-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pdai', '0008_alter_rf_model_bmi_alter_rf_model_hypertension'),
    ]

    operations = [
        migrations.CreateModel(
            name='interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.IntegerField()),
                ('onload', models.IntegerField()),
            ],
        ),
    ]
